### ISSUE TITLE
Repeated redshift autostart

### ISSUE THREAD

**Issue by edeustua** [tim241/dots#2]
Hi!

You are repeating the autostart of redshift twice. It first appears in line 10 and then again in 43 in `dots/.config/tim241/scripts/autostart.sh`
 
Cheers

**Comment by tim241** [comment]
Thank you! I didn't even notice that :+1: 

fixed in https://github.com/tim241/dots/commit/c6bec6f0fdb0f9303968ae0f708978cc0d3719a2
